apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::809102863946:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OXEPVZCAZH6R
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::809102863946:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-10T19:43:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1723"
  uid: 494d371e-72b7-4aeb-95de-5b24b07c470b
